### ISSUE TITLE
Teradata JDBC Driver Problem

### ISSUE THREAD

**Issue by ZidaneT** [sualeh/SchemaCrawler#102]
DatabaseMetaData from Teradata returns only "jdbs:teradata" from getUrl() method. Because of this, SchemaCrawler throws an exception when retrieving JDBC driver data (crawlDatabaseInfo in SchemaCrawler.crawl()), because it does not validate this URL as valid(in DriverManager.getDriver(url)). 

Could be something done to make this work? Maybe at least give an option not to retrieve driver info at all (not sure if the rest of code is depending on it or not)?

**Comment by sualeh** [comment]
Please send me a stack trace, and I will see how to address it.

**Comment by ZidaneT** [comment]
<pre>accurity.revenga.exceptions.ExternalToolException: SchemaCrawler was not able to create a connection.

	at accurity.revenga.browser.OnlineDBBrowserServiceImpl.crawlCatalog(OnlineDBBrowserServiceImpl.java:111)
	at accurity.revenga.browser.OnlineDBBrowserServiceImpl.getTable(OnlineDBBrowserServiceImpl.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:414)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy26.getTable(Unknown Source)
	at accurity.revenga.example.OnlineBrowserAbstractExample.tableRetrievalTest(OnlineBrowserAbstractExample.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
Caused by: schemacrawler.schemacrawler.SchemaCrawlerException: Exception retrieving database information: No suitable driver
	at schemacrawler.crawl.SchemaCrawler.crawlDatabaseInfo(SchemaCrawler.java:241)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:785)
	at schemacrawler.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:68)
	at accurity.revenga.browser.OnlineDBBrowserServiceImpl.crawlCatalog(OnlineDBBrowserServiceImpl.java:108)
	... 46 more
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at schemacrawler.crawl.DatabaseInfoRetriever.retrieveJdbcDriverInfo(DatabaseInfoRetriever.java:367)
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlDatabaseInfo$4(SchemaCrawler.java:203)
	at sf.util.StopWatch.time(StopWatch.java:156)
	at schemacrawler.crawl.SchemaCrawler.crawlDatabaseInfo(SchemaCrawler.java:202)
	... 49 more</pre>

**Comment by adriens** [comment]
@ZidaneT : is there a public open source jdc driver for this datanase ? If yes, can you please provide me the maven artifact groupid and id please ?

**Comment by sualeh** [comment]
Please use SchemaCrawler 14.11.01

**Comment by ZidaneT** [comment]
@adriens I don't think there is http://stackoverflow.com/questions/10796905/maven-dependency-for-teradata-jdbc-driver
@sualeh Thank you very much! It works. I found other problem, but here the message is clear : this driver does not support `getFunctions`. It is not important for me and probably it doesn't need a fix, but I think you should know:

<pre>
10:01:01.352 [main] ERROR a.r.b.OnlineDBBrowserServiceImpl - SchemaCrawler was not able to create a connection.
schemacrawler.schemacrawler.SchemaCrawlerException: Could not retrieve functions: [Teradata JDBC Driver] [TeraJDBC 15.00.00.20] [Error 165] [SQLState HY000] getFunctions: function not supported in this version
	at schemacrawler.crawl.SchemaCrawler.crawlRoutines(SchemaCrawler.java:353) ~[schemacrawler-14.11.01.jar:na]
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:798) ~[schemacrawler-14.11.01.jar:na]
	at schemacrawler.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:68) ~[schemacrawler-14.11.01.jar:na]
	at accurity.revenga.browser.OnlineDBBrowserServiceImpl.crawlCatalog(OnlineDBBrowserServiceImpl.java:112) [classes/:na]
	at accurity.revenga.browser.OnlineDBBrowserServiceImpl.getTable(OnlineDBBrowserServiceImpl.java:98) [classes/:na]
	at accurity.revenga.example.OnlineBrowserAbstractExample.connectionDomainObjectsCreation(OnlineBrowserAbstractExample.java:63) [classes/:na]
	at accurity.revenga.example.OnlineBrowserAbstractExample.test(OnlineBrowserAbstractExample.java:33) [classes/:na]
	at accurity.revenga.example.OnlineBrowserTeradataExample.main(OnlineBrowserTeradataExample.java:15) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
Exception in thread "main" accurity.revenga.exceptions.ExternalToolException: SchemaCrawler was not able to create a connection.
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at accurity.revenga.browser.OnlineDBBrowserServiceImpl.crawlCatalog(OnlineDBBrowserServiceImpl.java:115)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at accurity.revenga.browser.OnlineDBBrowserServiceImpl.getTable(OnlineDBBrowserServiceImpl.java:98)
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at accurity.revenga.example.OnlineBrowserAbstractExample.connectionDomainObjectsCreation(OnlineBrowserAbstractExample.java:63)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
	at accurity.revenga.example.OnlineBrowserAbstractExample.test(OnlineBrowserAbstractExample.java:33)
Caused by: java.sql.SQLException: [Teradata JDBC Driver] [TeraJDBC 15.00.00.20] [Error 165] [SQLState HY000] getFunctions: function not supported in this version
	at accurity.revenga.example.OnlineBrowserTeradataExample.main(OnlineBrowserTeradataExample.java:15)
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:94) ~[terajdbc4-15.00.00.20.jar:15.00.00.20]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:69) ~[terajdbc4-15.00.00.20.jar:15.00.00.20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.teradata.jdbc.TeraDatabaseMetaData.getFunctions(TeraDatabaseMetaData.java:5832) ~[terajdbc4-15.00.00.20.jar:15.00.00.20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at schemacrawler.crawl.RoutineRetriever.retrieveFunctions(RoutineRetriever.java:206) ~[schemacrawler-14.11.01.jar:na]
	at java.lang.reflect.Method.invoke(Method.java:498)
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlRoutines$7(SchemaCrawler.java:293) ~[schemacrawler-14.11.01.jar:na]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
	at sf.util.StopWatch.time(StopWatch.java:156) ~[schemacrawler-14.11.01.jar:na]
Caused by: schemacrawler.schemacrawler.SchemaCrawlerException: Could not retrieve functions: [Teradata JDBC Driver] [TeraJDBC 15.00.00.20] [Error 165] [SQLState HY000] getFunctions: function not supported in this version
	at schemacrawler.crawl.SchemaCrawler.crawlRoutines(SchemaCrawler.java:353)
	at schemacrawler.crawl.SchemaCrawler.crawlRoutines(SchemaCrawler.java:283) ~[schemacrawler-14.11.01.jar:na]
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:798)
	... 12 common frames omitted
	at schemacrawler.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:68)
	at accurity.revenga.browser.OnlineDBBrowserServiceImpl.crawlCatalog(OnlineDBBrowserServiceImpl.java:112)
	... 9 more
Caused by: java.sql.SQLException: [Teradata JDBC Driver] [TeraJDBC 15.00.00.20] [Error 165] [SQLState HY000] getFunctions: function not supported in this version
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:94)
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:69)
	at com.teradata.jdbc.TeraDatabaseMetaData.getFunctions(TeraDatabaseMetaData.java:5832)
	at schemacrawler.crawl.RoutineRetriever.retrieveFunctions(RoutineRetriever.java:206)
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlRoutines$7(SchemaCrawler.java:293)
	at sf.util.StopWatch.time(StopWatch.java:156)
	at schemacrawler.crawl.SchemaCrawler.crawlRoutines(SchemaCrawler.java:283)
	... 12 more

Process finished with exit code 1

</pre>

**Comment by sualeh** [comment]
I will fix that issue too. The Teradata JDBC driver does not follow JDBC specifications. It should throw a SQLFeatureNotSupportedException for getFunctions, or at the least a SQLException state HYC00 = Optional feature not implemented. Instead, it throws with a state of HY000 - General error.

**Comment by sualeh** [comment]
Please use SchemaCrawler 14.11.02

**Comment by adriens** [comment]
You're right @sualeh : login/pwd required to download...even the readme ;-(

http://downloads.teradata.com/download/connectivity/jdbc-driver

hence i assume they cannot be publicly distributed ...
