### ISSUE TITLE
MySQL Driver problem

### ISSUE THREAD

**Issue by ZidaneT** [sualeh/SchemaCrawler#104]
Aparrently, when I try to retrieve schema without specifying table inclusion rule, a SQLException occurs: 
Table name pattern can not be NULL or empty. 
<pre>
13:11:23.998 [main] ERROR a.r.b.OnlineDBBrowserServiceImpl - SchemaCrawler was not able to create a connection.
schemacrawler.schemacrawler.SchemaCrawlerException: Exception retrieving table information: Table name pattern can not be NULL or empty.
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:739) ~[schemacrawler-14.11.02.jar:na]
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:797) ~[schemacrawler-14.11.02.jar:na]
	at schemacrawler.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:68) ~[schemacrawler-14.11.02.jar:na]
	at accurity.revenga.browser.OnlineDBBrowserServiceImpl.crawlCatalog(OnlineDBBrowserServiceImpl.java:112) [classes/:na]
	at accurity.revenga.browser.OnlineDBBrowserServiceImpl.getTableNames(OnlineDBBrowserServiceImpl.java:59) [classes/:na]
	at accurity.revenga.example.OnlineBrowserBasicExample.connectionDomainObjectsCreation(OnlineBrowserBasicExample.java:50) [classes/:na]
	at accurity.revenga.example.OnlineBrowserBasicExample.test(OnlineBrowserBasicExample.java:33) [classes/:na]
	at accurity.revenga.example.OnlineBrowserMySQLExample.main(OnlineBrowserMySQLExample.java:20) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
Caused by: java.sql.SQLException: Table name pattern can not be NULL or empty.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:695) ~[mysql-connector-java-6.0.3.jar:6.0.3]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:663) ~[mysql-connector-java-6.0.3.jar:6.0.3]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:653) ~[mysql-connector-java-6.0.3.jar:6.0.3]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:638) ~[mysql-connector-java-6.0.3.jar:6.0.3]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:606) ~[mysql-connector-java-6.0.3.jar:6.0.3]
	at com.mysql.cj.jdbc.DatabaseMetaData.getTables(DatabaseMetaData.java:3835) ~[mysql-connector-java-6.0.3.jar:6.0.3]
	at schemacrawler.crawl.TableRetriever.retrieveTables(TableRetriever.java:114) ~[schemacrawler-14.11.02.jar:na]
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlTables$17(SchemaCrawler.java:570) ~[schemacrawler-14.11.02.jar:na]
	at sf.util.StopWatch.time(StopWatch.java:156) ~[schemacrawler-14.11.02.jar:na]
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:567) ~[schemacrawler-14.11.02.jar:na]
	... 12 common frames omitted

Process finished with exit code 1

</pre>
By the way, when I used this dependency (which I did by random),

```
<dependency>
         <groupId>net.sourceforge.schemacrawler</groupId>
         <artifactId>schemacrawler-mysql</artifactId>
         <version>10.10.05</version>
</dependency>
```
it actually works. This dependency uses 5.1.31 version of driver, so the problem occurs only in newer versions.

My (not complete) code: 
```
public List<String> getTableNames(Connection connection, String schema) {
        final SchemaCrawlerOptions options = new SchemaCrawlerOptions();
        final SchemaInfoLevel infoLevel = SchemaInfoLevelBuilder.minimum();
        infoLevel.setRetrieveRoutines(false);

        options.setSchemaInfoLevel(infoLevel);
        options.setSchemaInclusionRule(new RegularExpressionInclusionRule(schema));

        Catalog catalog = crawlCatalog(connection, options);

        return getNames(catalog.getTables());
    }

private Catalog crawlCatalog(Connection connection, SchemaCrawlerOptions options) {
        Catalog catalog;
        try {
            catalog = SchemaCrawlerUtility.getCatalog(getConnection(connection), options);
        } catch (Exception e) {
            LOGGER.error("SchemaCrawler was not able to create a connection.", e);
            throw new ExternalToolException("SchemaCrawler was not able to create a connection.", e);
        }
        return catalog;
    }
```

**Comment by sualeh** [comment]
This is a JDBC driver issue, and SchemaCrawler has no control over this. I would recommend:

1. You use the latest version of the MySQL JDBC driver

1. You use the latest schemacrawler-mysql jar file

1. You explicitly set a table name pattern in your code, like this: `options.setTableNamePattern("%")`

**Comment by sualeh** [comment]
Please make sure to use the correct MySQL database connection URL, following the documentation on [Driver/Datasource Class Names, URL Syntax and Configuration Properties for Connector/J](https://dev.mysql.com/doc/connector-j/6.0/en/connector-j-reference-configuration-properties.html)

In particular, you need to set
`nullNamePatternMatchesAll=true`
