### ISSUE TITLE
Documentation > How to graph database with jdbc only

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#123]
hi @sualeh , i'd like to graph a db2/400 database, from jt400 driver, straight from the jdbc url. Unfortunately i did not find how to provide the driver classname..and get the following stacktrace (complaining that the driver could be found, while it's in the lib dir)

```

schemacrawler -url jdbc:as400://robinnw -host=robinnw -user=XXX 
-schemas=sirh -password=XXX -c=schema -outputfile ./sirh_diagram_FP.pdf
-outputformat=pdf -infolevel=maximum database=XXX -loglevel=ALL

SEVERE: Could not find a suitable JDBC driver for database connection URL,
jdbc:as400://robinnw schemacrawler.schemacrawler.SchemaCrawlerSQLException:
Could not find a suitable JDBC driver for database connection URL,
jdbc:as400://robinnw at chemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getJdbcDriver(BaseDatabaseConnectionOptions.java:375) at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.createConnectionProperties(BaseDatabaseConnectionOptions.java:322) at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getConnection(BaseDatabaseConnectionOptions.java:143) at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getConnection(BaseDatabaseConnectionOptions.java:102) at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:127) at schemacrawler.Main.main(Main.java:90) Caused by: java.sql.SQLException: No suitable driver at java.sql.DriverManager.getDriver(DriverManager.java:315) at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getJdbcDriver(BaseDatabaseConnectionOptions.java:370) ... 5 more
```

Would you please have any hint to run successfully this command ? Thanks in advance for your help.

Cheers,

Adrien

**Comment by adriens** [comment]
current driver : ```jt400-9.3.jar```

I guess it's beacuase the classname is not declared in the jdbc driver...could we force the classname in the cli ?

**Comment by adriens** [comment]
In the cli help, we did not find the ```-driver=com.ibm.as400.access.AS400JDBCDriver``` switch : is it still available ?

**Comment by adriens** [comment]
```
May 16, 2017 2:58:33 PM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Could not find a suitable JDBC driver for database connection URL, jdbc:as400://robinnw
schemacrawler.schemacrawler.SchemaCrawlerSQLException: Could not find a suitable JDBC driver for database connection URL, jdbc:as400://robinnw
    at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getJdbcDriver(BaseDatabaseConnectionOptions.java:375)
    at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.createConnectionProperties(BaseDatabaseConnectionOptions.java:322)
    at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getConnection(BaseDatabaseConnectionOptions.java:143)
    at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getConnection(BaseDatabaseConnectionOptions.java:102)
    at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:127)
    at schemacrawler.Main.main(Main.java:90)
Caused by: java.sql.SQLException: No suitable driver
    at java.sql.DriverManager.getDriver(DriverManager.java:315)
    at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getJdbcDriver(BaseDatabaseConnectionOptions.java:370)

schemacrawler -driver=com.ibm.as400.access.AS400JDBCDriver -url=jdbc:as400://robinnw -user=opensirh -schemas=sirh -password=XHUZJ9BBQY -c=schema -outputfile=./sirh_diagram_FP.pdf -outputformat=pdf -infolevel=maximum database=S06A603R -loglevel=ALL
```

**Comment by sualeh** [comment]
@adriens, other people have tried this driver, and it is not JDBC compliant. However, you can load the driver using `-Djdbc.drivers=com.ibm.as400.access.AS400JDBCDriver` as described in [DriverManager](https://docs.oracle.com/javase/7/docs/api/java/sql/DriverManager.html)  javadocs.

**Comment by adriens** [comment]
Ok thanks for the feedback @sualeh

**Comment by adriens** [comment]
Juts for info, passig the -D jvm option did not fix the issue

**Comment by sualeh** [comment]
Bummer.
