### ISSUE TITLE
Crash on use of view using recursive table

### ISSUE THREAD

**Issue by rowet** [sualeh/SchemaCrawler#133]
$ cat crash.sql
```
CREATE TABLE model_parameter (
    param_name TEXT COLLATE NOCASE PRIMARY KEY,
    description TEXT,
    value NOT NULL
);
create view if not exists scenario_month (month) as
WITH RECURSIVE -- iterate months in scenario. This 'with section' is pretty ridiculous, but it works.
  scen_months(start_month, month_index, this_month) as (
     SELECT 
        (select strftime('%Y-%m-01', year || '-' || month || '-' || '01')),
        0,
        (select strftime('%Y%m01', year || '-' || month || '-' || '01'))
        from (select substr(value, 1, 4) as year, substr(value, 5, 2) as month
              from (select value from model_parameter where param_name = 'start_date' limit 1))
     UNION ALL
     SELECT start_month, month_index+1, (select strftime('%Y%m01', year || '-' || month || '-' || '01')
                                         from (select substr(value, 1, 4) as year, substr(value, 6, 2) as month
                                               from (select date(start_month, printf('+%i months', month_index + 1)) as value)))
     FROM scen_months
     LIMIT (select 12 * (end_year - start_year) + end_month - start_month -- Number of months in sim
            from
            ( (select substr(value, 1, 4) as start_year, substr(value, 5, 2) as start_month from model_parameter where param_name = 'start_date'),
              (select substr(value, 1, 4) as end_year, substr(value, 5, 2) as end_month from model_parameter where param_name = 'end_date') ))
)
SELECT this_month
FROM scen_months ;
```

$ sqlite3 crash.db < crash.sql
$ sh schemacrawler.sh -server=sqlite -database="crash.db" -infolevel=maximum -loglevel=CONFIG -password= -command=schema -portablenames -outputformat=pdf -outputfile="crash.pdf"
...
```
SchemaCrawler 14.16.01

Error: Exception retrieving table information: [SQLITE_CORRUPT]  The database disk image is malformed (malformed database schema (scenario_month) - near "(": syntax error)

Re-run SchemaCrawler with just the
-?
option for help

Or, re-run SchemaCrawler with an additional
-loglevel=CONFIG
option for details on the error
Jul 28, 2017 4:46:41 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: SchemaCrawler, v14.16.01
Jul 28, 2017 4:46:41 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: Command line: 
-server=sqlite
-database=/tmp/crash.db
-infolevel=maximum
-loglevel=CONFIG
-password=*****
-command=schema
-portablenames
-outputformat=pdf
-outputfile=/tmp/crash.pdf
Jul 28, 2017 4:46:41 PM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Exception retrieving table information: [SQLITE_CORRUPT]  The database disk image is malformed (malformed database schema (scenario_month) - near "(": syntax error)
schemacrawler.schemacrawler.SchemaCrawlerException: Exception retrieving table information: [SQLITE_CORRUPT]  The database disk image is malformed (malformed database schema (scenario_month) - near "(": syntax error)
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:759)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:817)
	at schemacrawler.tools.executable.BaseStagedExecutable.execute(BaseStagedExecutable.java:91)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:131)
	at schemacrawler.Main.main(Main.java:90)
Caused by: java.sql.SQLException: [SQLITE_CORRUPT]  The database disk image is malformed (malformed database schema (scenario_month) - near "(": syntax error)
	at org.sqlite.DB.newSQLException(DB.java:888)
	at org.sqlite.DB.newSQLException(DB.java:899)
	at org.sqlite.DB.throwex(DB.java:866)
	at org.sqlite.NativeDB.prepare(Native Method)
	at org.sqlite.DB.prepare(DB.java:208)
	at org.sqlite.Stmt.executeQuery(Stmt.java:155)
	at org.sqlite.MetaData.getTables(MetaData.java:1756)
	at schemacrawler.crawl.TableRetriever.retrieveTablesFromMetadata(TableRetriever.java:236)
	at schemacrawler.crawl.TableRetriever.retrieveTables(TableRetriever.java:118)
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlTables$17(SchemaCrawler.java:585)
	at sf.util.StopWatch.time(StopWatch.java:185)
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:582)
	... 4 more
```

**Comment by sualeh** [comment]
Please replace the version of the [SQLite Xerial JDBC driver jar file with the latest version, 3.19.3](https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc/3.19.3). Delete the old version of the jar in the `/lib` folder. Re-run SchemaCrawler with an additional `-routines=` command-line argument.

**Comment by rowet** [comment]
That fixes it. Without the additional -routines= parameter it fails with: "Error: Exception retrieving routine information: Cannot use null results"

**Comment by sualeh** [comment]
I will not fix this issue, since the latest version of the SQLite Xerial JDBC driver does not support features required for SchemaCrawler, such as getting primary key columns, and also reports inaccurate metadata. Please use the workaround when you need to.

**Comment by rowet** [comment]
Works fine for my purposes as is. Thanks!

**Comment by sualeh** [comment]
Glad to help.
