### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by buhtz** [sualeh/SchemaCrawler#14]
I just downloaded the last package and tried to start that under Lubuntu 14.04.3 LTS.

This is the result.

$ ./schemacrawler.sh
Exception in thread "main" java.lang.UnsupportedClassVersionError: schemacrawler/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by sualeh** [comment]
Please make sure you are using Java 8. Run:

`java -version`

**Comment by buhtz** [comment]
I think you mean Java from Oracle/Sun? I am using OpenJDK.

java version "1.7.0_85"
OpenJDK Runtime Environment (IcedTea 2.6.1) (7u85-2.6.1-5ubuntu0.14.04.1)
OpenJDK Server VM (build 24.85-b03, mixed mode)

This should work. Did you build the version check or is it a automatism.?

**Comment by sualeh** [comment]
You have the wrong version of Java. Please use Java 8. Oracle Java is preferred, but any Java 8 would work.

**Comment by buhtz** [comment]
This is not supportet in Ubuntu 14.04.3 LTS.

**Comment by sualeh** [comment]
Please take a look at [INSTALL ORACLE JAVA 8 IN UBUNTU OR LINUX MINT VIA PPA REPOSITORY JDK8](http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html)

**Comment by buhtz** [comment]
Oracle/Sun Java isn't a choice because of security.
