### ISSUE TITLE
trigger information retreive in PostGres Java API

### ISSUE THREAD

**Issue by sardineuser** [sualeh/SchemaCrawler#15]
Hello,
there is an issue retreiving trigger information on PostGres 9.4 in using the API : 
In fact the column name must be ACTION_TIMING in the select query instead of CONDITION_TIMING. Driver verion is the last available PostGres Java driver. Doesn't work too with the included driver in schemacrawler packages.

Here is the stack error : 

PM sf.util.DatabaseUtility executeSql
AVERTISSEMENT: Error executing: SELECT
  NULL AS TRIGGER_CATALOG,
  TRIGGER_SCHEMA,
  TRIGGER_NAME,
  EVENT_MANIPULATION,
  EVENT_OBJECT_CATALOG,
  EVENT_OBJECT_SCHEMA,
  EVENT_OBJECT_TABLE,
  ACTION_ORDER,
  ACTION_CONDITION,
  ACTION_STATEMENT,
  ACTION_ORIENTATION,
  CONDITION_TIMING,
  CREATED
FROM
  INFORMATION_SCHEMA.TRIGGERS

org.postgresql.util.PSQLException: ERREUR: la colonne � condition_timing � n'existe pas
  Position : 252
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:481)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:473)
	at sf.util.DatabaseUtility.executeSql(DatabaseUtility.java:118)
	at schemacrawler.crawl.TableExtRetriever.retrieveTriggerInformation(TableExtRetriever.java:450)
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlTables$23(SchemaCrawler.java:615)
	at sf.util.StopWatch.time(StopWatch.java:129)
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:612)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:742)
	at schemacrawler.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:60)

**Comment by sualeh** [comment]
I'll take a look.

**Comment by sualeh** [comment]
I have fixed this issue. It will be available in the next SchemaCrawler release.

**Comment by sardineuser** [comment]
Thanks a lot !

**Comment by sualeh** [comment]
Please use SchemaCrawler 14.04.04.
