### ISSUE TITLE
Postgres only > Remove the function retrieval from jdbc calls

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#23]
...as postgres does not implement it, ... and hence jdbc driver will not This could avoid a huge log file complaining about thinks like :

```
WARNING: JDBC driver does not support retrieving functions
java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc4.Jdbc4DatabaseMetaData.getFunction(String, String, String) is not yet implemented.
        at org.postgresql.Driver.notImplemented(Driver.java:670)
        at org.postgresql.jdbc4.AbstractJdbc4DatabaseMetaData.getFunctions(AbstractJdbc4DatabaseMetaData.java:87)
        at schemacrawler.crawl.RoutineRetriever.retrieveFunctions(RoutineRetriever.java:181)
        at schemacrawler.crawl.SchemaCrawler.lambda$crawlRoutines$8(SchemaCrawler.java:277)
        at schemacrawler.crawl.SchemaCrawler$$Lambda$45/388991153.call(Unknown Source)
        at sf.util.StopWatch.time(StopWatch.java:129)
```

**Comment by sualeh** [comment]
Resolved with https://github.com/sualeh/SchemaCrawler/commit/138019963deec47633be51970615fa9d37b8e66f

**Comment by adriens** [comment]
Yes, that's gr8 ! I saw it in the release note ! Thank U very much !
