### ISSUE TITLE
Exception retrieving routine information

### ISSUE THREAD

**Issue by BrandonZacharie** [sualeh/SchemaCrawler#46]
```
Mar 22, 2016 3:04:27 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: SchemaCrawler, v14.06.05
Mar 22, 2016 3:04:27 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: Command line: 
-g=./schemacrawler.config.properties
-infolevel=standard
-server=postgresql
-database=drank
-host=::1
-user=postgres
-password=*****
-command=graph
-outputformat=pdf
-outputfile=diagram.pdf
-tabletypes=table
-tables=^(?!.*spatial_ref_sys).*
-Gdpi=300
-loglevel=CONFIG
Mar 22, 2016 3:04:27 PM us.fatehi.commandlineparser.CommandLineUtility logSystemProperties
CONFIG: System properties: 
java.awt.graphicsenv=sun.awt.CGraphicsEnvironment
java.awt.printerjob=sun.lwawt.macosx.CPrinterJob
java.class.version=52.0
java.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/endorsed
java.ext.dirs=/Users/Brandon/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
java.io.tmpdir=/var/folders/bl/bqwbhwg939b1n19n4znq53f40000gn/T/
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_25-b17
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_25
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.25-b02
os.arch=x86_64
os.name=Mac OS X
os.version=10.11.4
Mar 22, 2016 3:04:27 PM us.fatehi.commandlineparser.CommandLineUtility logSystemProperties
CONFIG: Classpath: 
./_schemacrawler/lib/h2-1.4.191.jar
./_schemacrawler/lib/hsqldb-2.3.3.jar
./_schemacrawler/lib/jtds-1.3.1.jar
./_schemacrawler/lib/mariadb-java-client-1.3.5.jar
./_schemacrawler/lib/mysql-connector-java-5.1.38.jar
./_schemacrawler/lib/postgresql-9.4.1207.jar
./_schemacrawler/lib/schemacrawler-14.06.05.jar
./_schemacrawler/lib/schemacrawler-api-14.06.05-tests.jar
./_schemacrawler/lib/schemacrawler-db2-14.06.05.jar
./_schemacrawler/lib/schemacrawler-h2-14.06.05.jar
./_schemacrawler/lib/schemacrawler-hsqldb-14.06.05.jar
./_schemacrawler/lib/schemacrawler-lint-14.06.05.jar
./_schemacrawler/lib/schemacrawler-mariadb-14.06.05.jar
./_schemacrawler/lib/schemacrawler-mysql-14.06.05.jar
./_schemacrawler/lib/schemacrawler-offline-14.06.05.jar
./_schemacrawler/lib/schemacrawler-oracle-14.06.05.jar
./_schemacrawler/lib/schemacrawler-postgresql-14.06.05.jar
./_schemacrawler/lib/schemacrawler-sqlite-14.06.05.jar
./_schemacrawler/lib/schemacrawler-sqlserver-14.06.05.jar
./_schemacrawler/lib/schemacrawler-sybaseiq-14.06.05.jar
./_schemacrawler/lib/sqlite-jdbc-3.7.8.jar
./_schemacrawler/lib/xmlpull-1.1.3.1.jar
./_schemacrawler/lib/xpp3_min-1.1.4c.jar
./_schemacrawler/lib/xstream-1.4.8.jar
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, db2=schemacrawler.server.db2.DB2DatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, h2=schemacrawler.server.h2.H2DatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, hsqldb=schemacrawler.server.hsqldb.HyperSQLDatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, mariadb=schemacrawler.server.mariadb.MariaDBDatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, mysql=schemacrawler.server.mysql.MySQLDatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, offline=schemacrawler.tools.offline.OfflineDatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, oracle=schemacrawler.server.oracle.OracleDatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, postgresql=schemacrawler.server.postgresql.PostgreSQLDatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, sqlite=schemacrawler.tools.sqlite.SQLiteDatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, sqlserver=schemacrawler.server.sqlserver.SqlServerDatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, sybaseiq=schemacrawler.server.sybaseiq.SybaseIQDatabaseConnector
Mar 22, 2016 3:04:27 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry logRegisteredJdbcDrivers
CONFIG: Registered JDBC drivers, [com.mysql.fabric.jdbc.FabricMySQLDriver 5.1, com.mysql.jdbc.Driver 5.1, net.sourceforge.jtds.jdbc.Driver 1.3, org.h2.Driver 1.4, org.hsqldb.jdbc.JDBCDriver 2.3, org.mariadb.jdbc.Driver 1.3, org.postgresql.Driver 9.4, org.sqlite.JDBC 3.7, schemacrawler.tools.offline.jdbc.OfflineDriver 0.0]
Mar 22, 2016 3:04:27 PM schemacrawler.tools.commandline.SchemaCrawlerCommandLine <init>
INFO: Using database plugin, postgresql - PostgreSQL
Mar 22, 2016 3:04:27 PM schemacrawler.schemacrawler.Config loadProperties
INFO: Loading properties from file, /Users/Brandon/Dropbox/Projects/Pilcrow/Drank/Code/SQL/schemacrawler/schemacrawler.config.properties
Mar 22, 2016 3:04:27 PM schemacrawler.schemacrawler.Config loadProperties
CONFIG: Cannot load properties from file, /Users/Brandon/Dropbox/Projects/Pilcrow/Drank/Code/SQL/schemacrawler/schemacrawler.additional.config.properties
Mar 22, 2016 3:04:27 PM schemacrawler.tools.commandline.SchemaCrawlerOptionsParser getOptions
WARNING: Please provide a -schemas option for efficient retrieval of database metadata
Mar 22, 2016 3:04:27 PM schemacrawler.tools.commandline.SchemaCrawlerOptionsParser logOverride
INFO: Overriding tables inclusion rule from command-line to RegularExpressionRule@512ddf17-include/^(?!.*spatial_ref_sys).*/-exclude//]
Mar 22, 2016 3:04:27 PM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions getConnection
WARNING: Database password is not provided
Mar 22, 2016 3:04:27 PM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions getConnection
INFO: Making connection to jdbc:postgresql://::1:5432/drank?ApplicationName=SchemaCrawler
for user 'postgres', with properties {}
Mar 22, 2016 3:04:27 PM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions getConnection
INFO: Opened database connection, org.postgresql.jdbc.PgConnection@34ce8af7
Mar 22, 2016 3:04:27 PM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions logConnection
INFO: Connected to 
PostgreSQL 9.5.1 
using JDBC driver 
PostgreSQL Native Driver PostgreSQL 9.4.1207
Mar 22, 2016 3:04:27 PM schemacrawler.tools.executable.BaseStagedExecutable execute
INFO: Executing SchemaCrawler command, "graph"
Mar 22, 2016 3:04:27 PM schemacrawler.tools.executable.BaseStagedExecutable execute
CONFIG: schemacrawler.schemacrawler.SchemaCrawlerOptions@36d64342[
  childTableFilterDepth: 0
  columnInclusionRule: RegularExpressionRule@17c68925-include/.*/-exclude//]
  grepColumnInclusionRule: null
  grepDefinitionInclusionRule: null
  grepInvertMatch: false
  grepOnlyMatching: false
  grepRoutineColumnInclusionRule: null
  hideEmptyTables: false
  parentTableFilterDepth: 0
  routineColumnInclusionRule: IncludeAll
  routineInclusionRule: IncludeAll
  routineTypes: [procedure, function]
  schemaInclusionRule: IncludeAll
  schemaInfoLevel: standard
  sequenceInclusionRule: RegularExpressionRule@6fadae5d-include//-exclude/.*/]
  synonymInclusionRule: RegularExpressionRule@17f6480-include//-exclude/.*/]
  tableInclusionRule: RegularExpressionRule@512ddf17-include/^(?!.*spatial_ref_sys).*/-exclude//]
  tableNamePattern: null
  tableTypes: [table]
  title: 
]
Mar 22, 2016 3:04:27 PM schemacrawler.tools.executable.BaseStagedExecutable execute
CONFIG: schemacrawler.tools.options.OutputOptions@506e6d5e[
  inputEncodingCharset: UTF-8
  inputResource: null
  outputEncodingCharset: UTF-8
  outputFormatValue: pdf
  outputResource: /Users/Brandon/Dropbox/Projects/Pilcrow/Drank/Code/SQL/schemacrawler/diagram.pdf
]
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Database does not support catalogs
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Database supports schemas
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Database identifier quote string is """
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Supported table types are [temporary sequence, system toast table, foreign table, system toast index, system view, view, temporary table, table, system index, system table, sequence, index, temporary index, materialized view, temporary view, type]
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler crawlSchemas
INFO: Crawling schemas
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
INFO: Retrieving all schemas
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaRetriever retrieveAllCatalogs
INFO: Retrieving all catalogs
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveAllSchemas" results had 4 rows
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler crawlSchemas
INFO: Total time taken for "crawlSchemas" - 00:00:00.008 hours
-  0.0% - 00:00:00.008 - "retrieveSchemas"
-  0.0% - 00:00:00.000 - "sortAndFilterSchemas"

Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Crawling SchemaCrawler information
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Retrieving database information
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler lambda$crawlDatabaseInfo$4
INFO: Not retrieving additional database information, since this was not requested
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Retrieving JDBC driver information
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler lambda$crawlDatabaseInfo$6
INFO: Not retrieving additional JDBC driver information, since this was not requested
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Retrieving SchemaCrawler crawl information
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Total time taken for "crawlDatabaseInfo" - 00:00:00.016 hours
-  0.0% - 00:00:00.000 - "retrieveDatabaseInfo"
-  0.0% - 00:00:00.000 - "retrieveAdditionalDatabaseInfo"
-  0.0% - 00:00:00.000 - "retrieveJdbcDriverInfo"
-  0.0% - 00:00:00.000 - "retrieveAdditionalJdbcDriverInfo"
-  0.0% - 00:00:00.016 - "retrieveCrawlHeaderInfo"

Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler crawlColumnDataTypes
INFO: Crawling column data types
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler lambda$crawlColumnDataTypes$1
INFO: Retrieving system column data types
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler lambda$crawlColumnDataTypes$2
INFO: Not retrieving user column data types, since this was not requested
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler crawlColumnDataTypes
INFO: Total time taken for "crawlColumnDataTypes" - 00:00:00.190 hours
-  0.0% - 00:00:00.190 - "retrieveSystemColumnDataTypes"
-  0.0% - 00:00:00.000 - "retrieveUserDefinedColumnDataTypes"

Mar 22, 2016 3:04:27 PM schemacrawler.crawl.SchemaCrawler crawlTables
INFO: Crawling tables
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.TableRetriever retrieveTables
INFO: Retrieving tables
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveTables" results had 1 rows
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.TableRetriever retrieveTables
INFO: Retrieving tables
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveTables" results had 1 rows
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.TableRetriever retrieveTables
INFO: Retrieving tables
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveTables" results had 33 rows
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.TableColumnRetriever retrieveColumns
INFO: Retrieving table columns
Mar 22, 2016 3:04:27 PM schemacrawler.crawl.ForeignKeyRetriever retrieveForeignKeys
INFO: Retrieving foreign keys, using database metadata
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.SchemaCrawler lambda$crawlTables$22
INFO: Retrieving primary keys and indexes
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.IndexRetriever retrieveIndexes
INFO: Retrieving indexes, using database metadata
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.SchemaCrawler crawlTables
INFO: Total time taken for "crawlTables" - 00:00:01.019 hours
-  0.0% - 00:00:00.015 - "retrieveTables"
-  0.0% - 00:00:00.100 - "retrieveColumns"
-  0.0% - 00:00:00.679 - "retrieveForeignKeys"
-  0.0% - 00:00:00.018 - "filterAndSortTables"
-  0.0% - 00:00:00.206 - "retrieveIndexes"
-  0.0% - 00:00:00.000 - "retrieveTableConstraintInformation"
-  0.0% - 00:00:00.000 - "retrieveTriggerInformation"
-  0.0% - 00:00:00.000 - "retrieveViewInformation"
-  0.0% - 00:00:00.000 - "retrieveTableDefinitions"
-  0.0% - 00:00:00.001 - "retrieveIndexInformation"
-  0.0% - 00:00:00.000 - "retrieveAdditionalTableAttributes"
-  0.0% - 00:00:00.000 - "retrieveTablePrivileges"
-  0.0% - 00:00:00.000 - "retrieveAdditionalColumnAttributes"
-  0.0% - 00:00:00.000 - "retrieveTableColumnPrivileges"

Mar 22, 2016 3:04:28 PM schemacrawler.crawl.SchemaCrawler crawlRoutines
INFO: Crawling routines
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.RoutineRetriever retrieveProcedures
INFO: Retrieving procedures for, information_schema
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveProcedures" results had 13 rows
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.RoutineRetriever retrieveFunctions
INFO: Retrieving functions, information_schema
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.RoutineRetriever retrieveProcedures
INFO: Retrieving procedures for, pg_catalog
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveProcedures" results had 2810 rows
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.RoutineRetriever retrieveFunctions
INFO: Retrieving functions, pg_catalog
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.RoutineRetriever retrieveProcedures
INFO: Retrieving procedures for, public
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveProcedures" results had 1186 rows
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.RoutineRetriever retrieveFunctions
INFO: Retrieving functions, public
Mar 22, 2016 3:04:28 PM schemacrawler.crawl.SchemaCrawler lambda$crawlRoutines$9
INFO: Retrieving routine columns
Exception retrieving routine information: null
Re-run SchemaCrawler with the
-?
option for help
Or, re-run SchemaCrawler with an additional
-loglevel=CONFIG
option for details on the error
Mar 22, 2016 3:04:31 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: SchemaCrawler, v14.06.05
Mar 22, 2016 3:04:31 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: Command line: 
-g=./schemacrawler.config.properties
-infolevel=standard
-server=postgresql
-database=drank
-host=::1
-user=postgres
-password=*****
-command=graph
-outputformat=pdf
-outputfile=diagram.pdf
-tabletypes=table
-tables=^(?!.*spatial_ref_sys).*
-Gdpi=300
-loglevel=CONFIG
Mar 22, 2016 3:04:31 PM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Exception retrieving routine information: null
schemacrawler.schemacrawler.SchemaCrawlerException: Exception retrieving routine information: null
	at schemacrawler.crawl.SchemaCrawler.crawlRoutines(SchemaCrawler.java:346)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:759)
	at schemacrawler.tools.executable.BaseStagedExecutable.execute(BaseStagedExecutable.java:84)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:125)
	at schemacrawler.Main.main(Main.java:80)
Caused by: java.lang.NullPointerException
	at org.postgresql.jdbc.TypeInfoCache.getSQLType(TypeInfoCache.java:185)
	at org.postgresql.jdbc.TypeInfoCache.getSQLType(TypeInfoCache.java:180)
	at org.postgresql.jdbc.PgDatabaseMetaData.getProcedureColumns(PgDatabaseMetaData.java:1358)
	at org.postgresql.jdbc.PgDatabaseMetaData.getProcedureColumns(PgDatabaseMetaData.java:1146)
	at schemacrawler.crawl.RoutineRetriever.retrieveProcedureColumns(RoutineRetriever.java:252)
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlRoutines$9(SchemaCrawler.java:298)
	at schemacrawler.crawl.SchemaCrawler$$Lambda$47/1468303011.call(Unknown Source)
	at sf.util.StopWatch.time(StopWatch.java:129)
	at schemacrawler.crawl.SchemaCrawler.crawlRoutines(SchemaCrawler.java:288)
	... 4 more
```

This worked perfectly before but I have since made many changes to the schema.

**Comment by sualeh** [comment]
This is probably an [issue with the PostgreSQL JDBC driver](http://goo.gl/P3sqJy). Please use the command-line switch `-routines=`, so that SchemaCrawler does not attempt to obtain stored procedure metadata. Stored procedures are not shown on graphs anyway, so you will save some time too, this way.

**Comment by adriens** [comment]
@BrandonZacharie : just for info, could you please tell me which driver you are using ?

**Comment by sualeh** [comment]
[Adrien](@adriens), PostgreSQL driver 9.4.1207 - but this could be because he has user defined data types, perhaps?

**Comment by BrandonZacharie** [comment]
Yes, I have defined types (enums, to be specific). Also, procs have names like `dk_$person$_getByPhone`. That's legal but worth the mention in case the `$` is an issue somehow.

**Comment by BrandonZacharie** [comment]
@sualeh Thanks! `-routines=` works perfectly. Also, it didn't just save time, it now finishes instantly.

**Comment by sualeh** [comment]
Glad to hear, [Brandon](@BrandonZacharie). I am not sure why the PostgreSQL driver fails on those procedures - it may have a bug. If you need the stored procedure metadata for any reason, you could try to omit the problematic ones with a regular expression.

**Comment by BrandonZacharie** [comment]
I just ran a lint and saw the following:

```
...

Mar 22, 2016 8:10:15 PM schemacrawler.tools.executable.SchemaCrawlerExecutable executeOn
INFO: Executing as a query, lint
Name is null

...

Mar 22, 2016 8:10:15 PM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Name is null
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:236)
	at schemacrawler.tools.options.TextOutputFormat.valueOf(TextOutputFormat.java:27)
	at schemacrawler.tools.options.TextOutputFormat.fromFormat(TextOutputFormat.java:42)
	at schemacrawler.tools.text.operation.OperationExecutable.getDataTraversalHandler(OperationExecutable.java:141)
	at schemacrawler.tools.text.operation.OperationExecutable.executeOn(OperationExecutable.java:72)
	at schemacrawler.tools.executable.SchemaCrawlerExecutable.executeOn(SchemaCrawlerExecutable.java:91)
	at schemacrawler.tools.executable.BaseStagedExecutable.execute(BaseStagedExecutable.java:86)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:125)
	at schemacrawler.Main.main(Main.java:80)
```

I used `-routines=` as well to get it to work. I'm beginning to think it's not the proc names.

**Comment by sualeh** [comment]
This is a completely different issue. Please open another issue ticket, and I will take care of it.
