### ISSUE TITLE
NullPointerException: Name is null

### ISSUE THREAD

**Issue by BrandonZacharie** [sualeh/SchemaCrawler#47]
```
Mar 23, 2016 1:08:45 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: SchemaCrawler, v14.06.05
Mar 23, 2016 1:08:45 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: Command line: 
-server=postgresql
-database=drank
-user=postgres
-password=*****
-infolevel=standard
-routines=
-command=lint
-linterconfigs=lint.xml
-outputformat=html
-outputfile=lint.html
-loglevel=CONFIG
-linterconfigs=lint.xml
-outputformat=html
-outputfile=lint.html
Mar 23, 2016 1:08:45 PM us.fatehi.commandlineparser.CommandLineUtility logSystemProperties
CONFIG: System properties: 
java.awt.graphicsenv=sun.awt.CGraphicsEnvironment
java.awt.printerjob=sun.lwawt.macosx.CPrinterJob
java.class.version=52.0
java.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/endorsed
java.ext.dirs=/Users/Brandon/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
java.io.tmpdir=/var/folders/bl/bqwbhwg939b1n19n4znq53f40000gn/T/
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_25-b17
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_25
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.25-b02
os.arch=x86_64
os.name=Mac OS X
os.version=10.11.4
Mar 23, 2016 1:08:45 PM us.fatehi.commandlineparser.CommandLineUtility logSystemProperties
CONFIG: Classpath: 
./postgresql.jar
./schemacrawler-postgresql.jar
./schemacrawler.jar
Mar 23, 2016 1:08:45 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, postgresql=schemacrawler.server.postgresql.PostgreSQLDatabaseConnector
Mar 23, 2016 1:08:45 PM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry logRegisteredJdbcDrivers
CONFIG: Registered JDBC drivers, [org.postgresql.Driver 9.4]
Mar 23, 2016 1:08:45 PM schemacrawler.tools.commandline.SchemaCrawlerCommandLine <init>
INFO: Using database plugin, postgresql - PostgreSQL
Mar 23, 2016 1:08:45 PM schemacrawler.schemacrawler.Config loadProperties
CONFIG: Cannot load properties from file, /Users/Brandon/Dropbox/Projects/Pilcrow/Drank/Code/SQL/schemacrawler/schemacrawler.config.properties
Mar 23, 2016 1:08:45 PM schemacrawler.schemacrawler.Config loadProperties
CONFIG: Cannot load properties from file, /Users/Brandon/Dropbox/Projects/Pilcrow/Drank/Code/SQL/schemacrawler/schemacrawler.additional.config.properties
Mar 23, 2016 1:08:45 PM schemacrawler.tools.commandline.SchemaCrawlerOptionsParser getOptions
WARNING: Please provide a -schemas option for efficient retrieval of database metadata
Mar 23, 2016 1:08:45 PM schemacrawler.tools.commandline.SchemaCrawlerOptionsParser logOverride
INFO: Overriding routines inclusion rule from command-line to ExcludeAll
Mar 23, 2016 1:08:45 PM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions getConnection
WARNING: Database password is not provided
Mar 23, 2016 1:08:45 PM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions getConnection
INFO: Making connection to jdbc:postgresql://localhost:5432/drank?ApplicationName=SchemaCrawler
for user 'postgres', with properties {}
Mar 23, 2016 1:08:45 PM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions getConnection
INFO: Opened database connection, org.postgresql.jdbc.PgConnection@7382f612
Mar 23, 2016 1:08:45 PM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions logConnection
INFO: Connected to 
PostgreSQL 9.5.1 
using JDBC driver 
PostgreSQL Native Driver PostgreSQL 9.4.1207
Mar 23, 2016 1:08:45 PM schemacrawler.tools.executable.BaseStagedExecutable execute
INFO: Executing SchemaCrawler command, "lint"
Mar 23, 2016 1:08:45 PM schemacrawler.tools.executable.BaseStagedExecutable execute
CONFIG: schemacrawler.schemacrawler.SchemaCrawlerOptions@5577140b[
  childTableFilterDepth: 0
  columnInclusionRule: IncludeAll
  grepColumnInclusionRule: null
  grepDefinitionInclusionRule: null
  grepInvertMatch: false
  grepOnlyMatching: false
  grepRoutineColumnInclusionRule: null
  hideEmptyTables: false
  parentTableFilterDepth: 0
  routineColumnInclusionRule: IncludeAll
  routineInclusionRule: ExcludeAll
  routineTypes: [procedure, function]
  schemaInclusionRule: IncludeAll
  schemaInfoLevel: standard
  sequenceInclusionRule: RegularExpressionRule@77afea7d-include//-exclude/.*/]
  synonymInclusionRule: RegularExpressionRule@161cd475-include//-exclude/.*/]
  tableInclusionRule: IncludeAll
  tableNamePattern: null
  tableTypes: [BASE TABLE, TABLE, VIEW]
  title: 
]
Mar 23, 2016 1:08:45 PM schemacrawler.tools.executable.BaseStagedExecutable execute
CONFIG: schemacrawler.tools.options.OutputOptions@532760d8[
  inputEncodingCharset: UTF-8
  inputResource: null
  outputEncodingCharset: UTF-8
  outputFormatValue: html
  outputResource: /Users/Brandon/Dropbox/Projects/Pilcrow/Drank/Code/SQL/schemacrawler/lint.html
]
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Database does not support catalogs
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Database supports schemas
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Database identifier quote string is """
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Supported table types are [temporary sequence, system toast table, foreign table, system toast index, system view, view, temporary table, table, system index, system table, sequence, index, temporary index, materialized view, temporary view, type]
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler crawlSchemas
INFO: Crawling schemas
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
INFO: Retrieving all schemas
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaRetriever retrieveAllCatalogs
INFO: Retrieving all catalogs
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveAllSchemas" results had 4 rows
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler crawlSchemas
INFO: Total time taken for "crawlSchemas" - 00:00:00.013 hours
-  0.0% - 00:00:00.013 - "retrieveSchemas"
-  0.0% - 00:00:00.000 - "sortAndFilterSchemas"

Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Crawling SchemaCrawler information
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Retrieving database information
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler lambda$crawlDatabaseInfo$4
INFO: Not retrieving additional database information, since this was not requested
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Retrieving JDBC driver information
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler lambda$crawlDatabaseInfo$6
INFO: Not retrieving additional JDBC driver information, since this was not requested
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Retrieving SchemaCrawler crawl information
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Total time taken for "crawlDatabaseInfo" - 00:00:00.013 hours
-  0.0% - 00:00:00.000 - "retrieveDatabaseInfo"
-  0.0% - 00:00:00.000 - "retrieveAdditionalDatabaseInfo"
-  0.0% - 00:00:00.000 - "retrieveJdbcDriverInfo"
-  0.0% - 00:00:00.000 - "retrieveAdditionalJdbcDriverInfo"
-  0.0% - 00:00:00.013 - "retrieveCrawlHeaderInfo"

Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler crawlColumnDataTypes
INFO: Crawling column data types
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler lambda$crawlColumnDataTypes$1
INFO: Retrieving system column data types
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler lambda$crawlColumnDataTypes$2
INFO: Not retrieving user column data types, since this was not requested
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler crawlColumnDataTypes
INFO: Total time taken for "crawlColumnDataTypes" - 00:00:00.187 hours
-  0.0% - 00:00:00.187 - "retrieveSystemColumnDataTypes"
-  0.0% - 00:00:00.000 - "retrieveUserDefinedColumnDataTypes"

Mar 23, 2016 1:08:45 PM schemacrawler.crawl.SchemaCrawler crawlTables
INFO: Crawling tables
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.TableRetriever retrieveTables
INFO: Retrieving tables
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveTables" results had 1 rows
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.TableRetriever retrieveTables
INFO: Retrieving tables
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveTables" results had 1 rows
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.TableRetriever retrieveTables
INFO: Retrieving tables
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.MetadataResultSet close
INFO: "retrieveTables" results had 37 rows
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.TableColumnRetriever retrieveColumns
INFO: Retrieving table columns
Mar 23, 2016 1:08:45 PM schemacrawler.crawl.ForeignKeyRetriever retrieveForeignKeys
INFO: Retrieving foreign keys, using database metadata
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.SchemaCrawler lambda$crawlTables$22
INFO: Retrieving primary keys and indexes
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.IndexRetriever retrieveIndexes
INFO: Retrieving indexes, using database metadata
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.SchemaCrawler crawlTables
INFO: Total time taken for "crawlTables" - 00:00:01.088 hours
-  0.0% - 00:00:00.016 - "retrieveTables"
-  0.0% - 00:00:00.122 - "retrieveColumns"
-  0.0% - 00:00:00.704 - "retrieveForeignKeys"
-  0.0% - 00:00:00.026 - "filterAndSortTables"
-  0.0% - 00:00:00.220 - "retrieveIndexes"
-  0.0% - 00:00:00.000 - "retrieveTableConstraintInformation"
-  0.0% - 00:00:00.000 - "retrieveTriggerInformation"
-  0.0% - 00:00:00.000 - "retrieveViewInformation"
-  0.0% - 00:00:00.000 - "retrieveTableDefinitions"
-  0.0% - 00:00:00.000 - "retrieveIndexInformation"
-  0.0% - 00:00:00.000 - "retrieveAdditionalTableAttributes"
-  0.0% - 00:00:00.000 - "retrieveTablePrivileges"
-  0.0% - 00:00:00.000 - "retrieveAdditionalColumnAttributes"
-  0.0% - 00:00:00.000 - "retrieveTableColumnPrivileges"

Mar 23, 2016 1:08:46 PM schemacrawler.crawl.SchemaCrawler crawlRoutines
INFO: Crawling routines
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.RoutineRetriever retrieveProcedures
INFO: Not retrieving procedures, since this was not requested
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.RoutineRetriever retrieveFunctions
INFO: Not retrieving functions, since this was not requested
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.RoutineRetriever retrieveProcedures
INFO: Not retrieving procedures, since this was not requested
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.RoutineRetriever retrieveFunctions
INFO: Not retrieving functions, since this was not requested
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.RoutineRetriever retrieveProcedures
INFO: Not retrieving procedures, since this was not requested
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.RoutineRetriever retrieveFunctions
INFO: Not retrieving functions, since this was not requested
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.SchemaCrawler lambda$crawlRoutines$9
INFO: Retrieving routine columns
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.SchemaCrawler crawlRoutines
INFO: Total time taken for "crawlRoutines" - 00:00:00.004 hours
-  0.0% - 00:00:00.002 - "retrieveRoutines"
-  0.0% - 00:00:00.000 - "retrieveRoutineColumns"
-  0.0% - 00:00:00.002 - "filterRoutines"
-  0.0% - 00:00:00.000 - "retrieveRoutineInformation"

Mar 23, 2016 1:08:46 PM schemacrawler.crawl.SchemaCrawler crawlSynonyms
INFO: Not retrieving synonyms, since this was not requested
Mar 23, 2016 1:08:46 PM schemacrawler.crawl.SchemaCrawler crawlSequences
INFO: Not retrieving sequences, since this was not requested
Mar 23, 2016 1:08:46 PM schemacrawler.tools.executable.SchemaCrawlerExecutable executeOn
INFO: Executing as a query, lint
Name is null
Re-run SchemaCrawler with the
-?
option for help
Or, re-run SchemaCrawler with an additional
-loglevel=CONFIG
option for details on the error
Mar 23, 2016 1:08:46 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: SchemaCrawler, v14.06.05
Mar 23, 2016 1:08:46 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: Command line: 
-server=postgresql
-database=drank
-user=postgres
-password=*****
-infolevel=standard
-routines=
-command=lint
-linterconfigs=lint.xml
-outputformat=html
-outputfile=lint.html
-loglevel=CONFIG
-linterconfigs=lint.xml
-outputformat=html
-outputfile=lint.html
Mar 23, 2016 1:08:46 PM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Name is null
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:236)
	at schemacrawler.tools.options.TextOutputFormat.valueOf(TextOutputFormat.java:27)
	at schemacrawler.tools.options.TextOutputFormat.fromFormat(TextOutputFormat.java:42)
	at schemacrawler.tools.text.operation.OperationExecutable.getDataTraversalHandler(OperationExecutable.java:141)
	at schemacrawler.tools.text.operation.OperationExecutable.executeOn(OperationExecutable.java:72)
	at schemacrawler.tools.executable.SchemaCrawlerExecutable.executeOn(SchemaCrawlerExecutable.java:91)
	at schemacrawler.tools.executable.BaseStagedExecutable.execute(BaseStagedExecutable.java:86)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:125)
	at schemacrawler.Main.main(Main.java:80)
```

**Comment by sualeh** [comment]
You need to have `schemacrawler-lint-14.06.05.jar` on your classpath. Your current classpath is:
```
CONFIG: Classpath: 
./postgresql.jar
./schemacrawler-postgresql.jar
./schemacrawler.jar
```

**Comment by BrandonZacharie** [comment]
Perfect. Thanks!

**Comment by sualeh** [comment]
You're welcome. Please use the latest version of SchemaCrawler, since it has some lint enhancements.
