### ISSUE TITLE
catalog.getTables(schema) returns empty list

### ISSUE THREAD

**Issue by AlexLuya** [sualeh/SchemaCrawler#85]
Hello,
     blow is my test code,schema got printed out,but tables not,doesn't SchemaCrawler support MariaDB yet.
```
public static void main(final String[] args) throws Exception
	{
		// Create a database connection
		final DataSource dataSource = new DatabaseConnectionOptions("jdbc:mariadb://host:3306/vsi_dw_etl");
		final Connection connection = dataSource.getConnection("user", "password");

		// Create the options
		final SchemaCrawlerOptions options = new SchemaCrawlerOptions();
		options.setSchemaInfoLevel(SchemaInfoLevelBuilder.standard());

		options.setTableTypes(Lists.newArrayList("TABLE","VIEW","SYSTEM	TABLE"));
		// options.setRoutineInclusionRule(new ExcludeAll());
		options.setSchemaInclusionRule(new RegularExpressionInclusionRule("vsi_dw_etl"));

		// Get the schema definition
		final Catalog catalog = SchemaCrawlerUtility.getCatalog(connection, options);

		for (final Schema schema : catalog.getSchemas())
		{
			System.out.print("c--> " + schema.getCatalogName() + "\n");
			
			for (final Table table : catalog.getTables(schema))
			{

				System.out.print("o--> " + table);
				if (table instanceof View)
				{
					System.out.println(" (VIEW)");
				} else
				{
					System.out.println();
				}

				for (final Column column : table.getColumns())
				{
					System.out.println("     o--> " + column + " (" + column.getColumnDataType() + ")");
				}
			}
		}
	}
```

**Comment by sualeh** [comment]
SchemaCrawler does support MariaDB. MariaDB calls tables ["BASE TABLE"](https://mariadb.com/kb/en/sql-99/base-table/). So, please add "BASE TABLE" to your list in `options.setTableTypes(Lists.newArrayList("TABLE","VIEW","SYSTEM TABLE"));`

**Comment by AlexLuya** [comment]
Thanks,I followed your suggestion,but still not table name got printed out

**Comment by sualeh** [comment]
Please show your updated code.

**Comment by AlexLuya** [comment]
just changed blow 

`options.setTableTypes(Lists.newArrayList("TABLE","VIEW","SYSTEM TABLE"));`

to
`options.setTableTypes(Lists.newArrayList("TABLE","VIEW","SYSTEM TABLE","BASE TABLE"));`

**Comment by sualeh** [comment]
Try commenting that line completely.
`// options.setTableTypes(Lists.newArrayList("TABLE","VIEW","SYSTEM TABLE","BASE TABLE")); `

**Comment by AlexLuya** [comment]
don't work,still only database names got printed out.

**Comment by AlexLuya** [comment]
How can reopen this bug,or should I create new one?

**Comment by sualeh** [comment]
In order to file a bug, you need to provide a detailed log file. Please run SchemaCrawler from the command-line, with an additional `-loglevel=ALL` argument, and provide the logs.

**Comment by AlexLuya** [comment]
strangely,command line can print out all columns,would you please tell me what is wrong in my code.

**Comment by sualeh** [comment]
Try getting rid of the schema exclusion rule?

**Comment by AlexLuya** [comment]
Tried your suggestion,same result,and I added 
`options.setTableNamePattern("*");`
try again,same result.

**Comment by AlexLuya** [comment]
`options.setTableNamePattern("%");`

will give table list,but got another error:
```
Exception in thread "main" schemacrawler.schemacrawler.SchemaCrawlerException: Could not retrieve columns for table assessment.assessment_fact: Column name pattern can not be NULL or empty.
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:721)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:787)
	at schemacrawler.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:68)
	at com.dsc.selenium.db.ApiExample.main(ApiExample.java:50)
Caused by: java.sql.SQLException: Column name pattern can not be NULL or empty.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:695)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:663)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:653)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:638)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:606)
	at com.mysql.cj.jdbc.DatabaseMetaData.getColumns(DatabaseMetaData.java:2078)
	at schemacrawler.crawl.TableColumnRetriever.retrieveColumnsFromMetadata(TableColumnRetriever.java:299)
	at schemacrawler.crawl.TableColumnRetriever.retrieveColumns(TableColumnRetriever.java:107)
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlTables$27(SchemaCrawler.java:573)
	at sf.util.StopWatch.time(StopWatch.java:156)
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:570)
	... 3 more
```

`where to set column column name pattern?`

**Comment by sualeh** [comment]
You are not providing complete information. I do not know what version of SchemaCrawler you are using, what type of operating system, database name and version, JDBC driver name and version, and so on. You have posted information on StackOverflow that indicates you are using MySQL, but this issue is about MariaDB, so I am completely confused on what exactly you are trying to do.

**Comment by AlexLuya** [comment]
Sorry for that,I am using:
  ```
 schemacrawler-14.09.03-main
  Ubuntu 16.04 64bit
  MariaDB 10.2.1-MariaDB-1~xenial
  (I assumed mariadb may not be supported yet,so switch between blow two drivers,but neither works)
  mysql-connector-java-6.0.3
 mariadb-java-client-1.4.6
```
  By the way,with same configuration,blow command gives expected output
**./schemacrawler.sh -server=mysql -database=target_db -user=root -password=password -infolevel=ALL -command=schema
wi**

**Comment by sualeh** [comment]
I still have no idea what the classpath is, and I am really not sure if you are Java programmer if you cannot provide relevant information to help debug, and are not able to debug for yourself. You have not even provided the logs that I asked for.

**Comment by AlexLuya** [comment]
Shame for me,
```
Aug 12, 2016 8:44:48 AM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: SchemaCrawler, v14.09.03
Aug 12, 2016 8:44:48 AM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: Command line: 
-server=mysql
-database=assessment
-user=root
-password=*****
-command=schema
-infolevel=WARNING
-loglevel=ALL
Aug 12, 2016 8:44:48 AM us.fatehi.commandlineparser.CommandLineUtility logSystemProperties
CONFIG: System properties: 
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
java.awt.printerjob=sun.print.PSPrinterJob
java.class.version=52.0
java.endorsed.dirs=/usr/lib/jvm/java-8-oracle/jre/lib/endorsed
java.ext.dirs=/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext
java.home=/usr/lib/jvm/java-8-oracle/jre
java.io.tmpdir=/tmp
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_101-b13
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_101
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.101-b13
os.arch=amd64
os.name=Linux
os.version=4.4.0-34-generic
Aug 12, 2016 8:44:48 AM us.fatehi.commandlineparser.CommandLineUtility logSystemProperties
CONFIG: Classpath: 
lib/h2-1.4.192.jar
lib/hsqldb-2.3.4.jar
lib/jtds-1.3.1.jar
lib/mysql-connector-java-6.0.3.jar
lib/postgresql-9.4.1208.jar
lib/schemacrawler-14.09.03.jar
lib/schemacrawler-api-14.09.03-tests.jar
lib/schemacrawler-db2-14.09.03.jar
lib/schemacrawler-h2-14.09.03.jar
lib/schemacrawler-hsqldb-14.09.03.jar
lib/schemacrawler-lint-14.09.03.jar
lib/schemacrawler-mysql-14.09.03.jar
lib/schemacrawler-offline-14.09.03.jar
lib/schemacrawler-oracle-14.09.03.jar
lib/schemacrawler-postgresql-14.09.03.jar
lib/schemacrawler-sqlite-14.09.03.jar
lib/schemacrawler-sqlserver-14.09.03.jar
lib/schemacrawler-sybaseiq-14.09.03.jar
lib/sqlite-jdbc-3.7.8.jar
lib/xmlpull-1.1.3.1.jar
lib/xpp3_min-1.1.4c.jar
lib/xstream-1.4.9.jar
Aug 12, 2016 8:44:48 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, db2=schemacrawler.server.db2.DB2DatabaseConnector
Aug 12, 2016 8:44:48 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, h2=schemacrawler.server.h2.H2DatabaseConnector
Aug 12, 2016 8:44:48 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, hsqldb=schemacrawler.server.hsqldb.HyperSQLDatabaseConnector
Aug 12, 2016 8:44:48 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, mysql=schemacrawler.server.mysql.MySQLDatabaseConnector
Aug 12, 2016 8:44:48 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, offline=schemacrawler.tools.offline.OfflineDatabaseConnector
Aug 12, 2016 8:44:48 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, oracle=schemacrawler.server.oracle.OracleDatabaseConnector
Aug 12, 2016 8:44:48 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, postgresql=schemacrawler.server.postgresql.PostgreSQLDatabaseConnector
Aug 12, 2016 8:44:48 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, sqlite=schemacrawler.tools.sqlite.SQLiteDatabaseConnector
Aug 12, 2016 8:44:49 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, sqlserver=schemacrawler.server.sqlserver.SqlServerDatabaseConnector
Aug 12, 2016 8:44:49 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry loadDatabaseConnectorRegistry
CONFIG: Loading database connector, sybaseiq=schemacrawler.server.sybaseiq.SybaseIQDatabaseConnector
Aug 12, 2016 8:44:49 AM schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry logRegisteredJdbcDrivers
CONFIG: Registered JDBC drivers, [com.mysql.cj.jdbc.Driver 6.0, net.sourceforge.jtds.jdbc.Driver 1.3, org.h2.Driver 1.4, org.hsqldb.jdbc.JDBCDriver 2.3, org.postgresql.Driver 9.4, org.sqlite.JDBC 3.7, schemacrawler.tools.offline.jdbc.OfflineDriver 0.0]
Aug 12, 2016 8:44:49 AM schemacrawler.tools.commandline.SchemaCrawlerCommandLine <init>
INFO: Using database plugin, mysql - MySQL
Aug 12, 2016 8:44:49 AM schemacrawler.schemacrawler.Config loadProperties
CONFIG: Cannot load properties from file, /home/alex/Software/schemacrawler-14.09.03-main/_schemacrawler/schemacrawler.config.properties
Aug 12, 2016 8:44:49 AM schemacrawler.schemacrawler.Config loadProperties
CONFIG: Cannot load properties from file, /home/alex/Software/schemacrawler-14.09.03-main/_schemacrawler/schemacrawler.additional.config.properties
Aug 12, 2016 8:44:49 AM schemacrawler.tools.options.InfoLevel valueOfFromString
INFO: Unknown infolevel, WARNING
Aug 12, 2016 8:44:49 AM schemacrawler.tools.commandline.SchemaCrawlerOptionsParser getOptions
WARNING: Please provide a -schemas option for efficient retrieval of database metadata
Aug 12, 2016 8:44:49 AM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions getConnection
INFO: Making connection to jdbc:mysql://localhost:3306/assessment?nullNamePatternMatchesAll=true&logger=Jdk14Logger&dumpQueriesOnException=true&dumpMetadataOnColumnNotFound=true&maxQuerySizeToLog=4096
for user 'root', with properties {}
Aug 12, 2016 8:44:49 AM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions getConnection
INFO: Opened database connection, com.mysql.cj.jdbc.ConnectionImpl@d8355a8
Aug 12, 2016 8:44:49 AM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions logConnection
INFO: Connected to 
MySQL 5.5.5-10.2.1-MariaDB-1~xenial 
using JDBC driver 
MySQL Connector Java mysql-connector-java-6.0.3 ( Revision: 9fb85a76ccb7506157e668f1516464a46e317d4a )
Aug 12, 2016 8:44:49 AM schemacrawler.tools.executable.BaseStagedExecutable execute
INFO: Executing SchemaCrawler command, "schema"
Aug 12, 2016 8:44:49 AM schemacrawler.tools.executable.BaseStagedExecutable execute
CONFIG: schemacrawler.schemacrawler.SchemaCrawlerOptions@4501b7af[
  childTableFilterDepth: 0
  columnInclusionRule: IncludeAll
  grepColumnInclusionRule: null
  grepDefinitionInclusionRule: null
  grepInvertMatch: false
  grepOnlyMatching: false
  grepRoutineColumnInclusionRule: null
  hideEmptyTables: false
  parentTableFilterDepth: 0
  routineColumnInclusionRule: IncludeAll
  routineInclusionRule: IncludeAll
  routineTypes: [procedure, function]
  schemaInclusionRule: IncludeAll
  schemaInfoLevel: unknown
  sequenceInclusionRule: RegularExpressionRule@6f7fd0e6-include//-exclude/.*/]
  synonymInclusionRule: RegularExpressionRule@47c62251-include//-exclude/.*/]
  tableInclusionRule: IncludeAll
  tableNamePattern: null
  tableTypes: [BASE TABLE, TABLE, VIEW]
  title: 
]
Aug 12, 2016 8:44:49 AM schemacrawler.tools.executable.BaseStagedExecutable execute
CONFIG: schemacrawler.tools.options.OutputOptions@3e6fa38a[
  inputEncodingCharset: UTF-8
  inputResource: null
  outputEncodingCharset: UTF-8
  outputFormatValue: text
  outputResource: null
]
Aug 12, 2016 8:44:49 AM schemacrawler.tools.executable.BaseStagedExecutable execute
FINE: 
database: assessment
host: localhost
port: 3306
schemacrawler.format.append_output: false
schemacrawler.format.hide_constraint_names: false
schemacrawler.format.hide_foreignkey_names: false
schemacrawler.format.hide_index_names: false
schemacrawler.format.hide_primarykey_names: false
schemacrawler.format.hide_remarks: false
schemacrawler.format.hide_routine_specific_names: false
schemacrawler.format.hide_trigger_names: false
schemacrawler.format.hide_weak_associations: false
schemacrawler.format.no_footer: false
schemacrawler.format.no_header: false
schemacrawler.format.no_info: false
schemacrawler.format.no_schema_colors: false
schemacrawler.format.show_ordinal_numbers: false
schemacrawler.format.show_row_counts: false
schemacrawler.format.show_standard_column_type_names: false
schemacrawler.format.show_unqualified_names: false
schemacrawler.format.sort_alphabetically.routine_columns: false
schemacrawler.format.sort_alphabetically.routines: false
schemacrawler.format.sort_alphabetically.table_columns: false
schemacrawler.format.sort_alphabetically.table_foreignkeys: false
schemacrawler.format.sort_alphabetically.table_indexes: false
schemacrawler.format.sort_alphabetically.tables: true
url: jdbc:mysql://${host}:${port}/${database}?nullNamePatternMatchesAll=true&logger=Jdk14Logger&dumpQueriesOnException=true&dumpMetadataOnColumnNotFound=true&maxQuerySizeToLog=4096
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Database supports catalogs
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Database does not support schemas
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Database identifier quote string is "`"
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.RetrieverConnection <init>
CONFIG: Supported table types are [table, system table, system view, view, local temporary]
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaCrawler crawlSchemas
INFO: Crawling schemas
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaRetriever retrieveAllSchemasFromInformationSchemaViews
FINE: Schemata SQL statement was not provided
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
INFO: Retrieving all schemas
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaRetriever retrieveAllCatalogs
INFO: Retrieving all catalogs
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaRetriever retrieveAllCatalogs
FINER: Retrieved catalogs, [assessment, information_schema, performance_schema, vsi_dw_etl, mysql, icare_dw_dev]
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
FINER: Retrieving schema: assessment --> null
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
FINER: Retrieving schema: information_schema --> null
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
FINER: Retrieving schema: performance_schema --> null
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
FINER: Retrieving schema: vsi_dw_etl --> null
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
FINER: Retrieving schema: mysql --> null
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
FINER: Retrieving schema: icare_dw_dev --> null
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaCrawler crawlSchemas
INFO: Total time taken for "crawlSchemas" - 00:00:00.007 hours
-  0.0% - 00:00:00.007 - "retrieveSchemas"
-  0.0% - 00:00:00.000 - "sortAndFilterSchemas"

Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Crawling SchemaCrawler information
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Retrieving database information
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaCrawler lambda$crawlDatabaseInfo$12
INFO: Not retrieving additional database information, since this was not requested
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Retrieving JDBC driver information
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaCrawler lambda$crawlDatabaseInfo$14
INFO: Not retrieving additional JDBC driver information, since this was not requested
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Retrieving SchemaCrawler crawl information
Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Total time taken for "crawlDatabaseInfo" - 00:00:00.006 hours
-  0.0% - 00:00:00.000 - "retrieveDatabaseInfo"
-  0.0% - 00:00:00.000 - "retrieveAdditionalDatabaseInfo"
-  0.0% - 00:00:00.001 - "retrieveJdbcDriverInfo"
-  0.0% - 00:00:00.000 - "retrieveAdditionalJdbcDriverInfo"
-  0.0% - 00:00:00.005 - "retrieveCrawlHeaderInfo"

Aug 12, 2016 8:44:49 AM schemacrawler.crawl.SchemaCrawler crawlColumnDataTypes
INFO: Crawling column data types
.....(if left is needed,I can provide)
```

**Comment by sualeh** [comment]
So, why are you using the MySQL JDBC driver to connect to MariaDB?

**Comment by AlexLuya** [comment]
Seems picked by itself

**Comment by sualeh** [comment]
Ok, I am sorry I cannot help you any more. Do you understand that the MariaDB driver is not on your classpath? Please look at this page: http://sualeh.github.io/SchemaCrawler/consulting.html

**Comment by AlexLuya** [comment]
Yes,I haven't MariaDB in 

`schemacrawler-14.09.03-main/_schemacrawler/lib`

but with command line

`./schemacrawler.sh -server=mysql -database=target_db -user=root -password=password -infolevel=ALL -command=schema`

gives `expected output`,if changing 

` -server=mysql to -server=maridb`

I got:

```
Aug 12, 2016 9:05:05 AM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Unsupported server, mariadb
schemacrawler.schemacrawler.SchemaCrawlerCommandLineException: Unsupported server, mariadb
	at schemacrawler.tools.commandline.DatabaseServerTypeParser.getOptions(DatabaseServerTypeParser.java:65)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.<init>(SchemaCrawlerCommandLine.java:81)
	at schemacrawler.Main.main(Main.java:89)
```

Within eclipse,I have both mariadb driver and mysql driver in classpath,

if 

`final DataSource dataSource = new DatabaseConnectionOptions("`jdbc:mariadb`://localhost:3306/assessment");`

only database name got printed out,and if 

`final DataSource dataSource = new DatabaseConnectionOptions("`jdbc:mysql`://localhost:3306/assessment");`

I got:

```
Exception in thread "main" schemacrawler.schemacrawler.SchemaCrawlerException: Could not retrieve columns for table assessment.assessment_fact: Column name pattern can not be NULL or empty.
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:721)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:787)
	at schemacrawler.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:68)
	at com.dsc.selenium.db.ApiExample.main(ApiExample.java:50)
Caused by: java.sql.SQLException: Column name pattern can not be NULL or empty.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:695)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:663)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:653)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:638)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:606)
	at com.mysql.cj.jdbc.DatabaseMetaData.getColumns(DatabaseMetaData.java:2078)
	at schemacrawler.crawl.TableColumnRetriever.retrieveColumnsFromMetadata(TableColumnRetriever.java:299)
	at schemacrawler.crawl.TableColumnRetriever.retrieveColumns(TableColumnRetriever.java:107)
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlTables$27(SchemaCrawler.java:573)
	at sf.util.StopWatch.time(StopWatch.java:156)
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:570)
	... 3 more

```

**Comment by AlexLuya** [comment]
Finally,I figured it out:
`options.setTableTypes(Lists.newArrayList("BASE TABLE","TABLE","VIEW","UNKNOWN"));`

Caution:with MariaDB,table types is "**UNKNOWN**"
