### ISSUE TITLE
Cannot connect to SQL Server 2014 Express

### ISSUE THREAD

**Issue by schemacrawler** [sualeh/SchemaCrawler#90]
After one day trying to connect to SQL Server 2014 Express I give up.

- Mixed authentication has been enabled in SQL Server 2014
- The SQL Server 2014 has been configured to enable tcp/ip connection
- The firewall has been configured to allow connections on the port 1433 and for sqlserver.exe
- A sql server login named "sc" with password "sc" has been created and mapped to a test database

If I use the management studio I can connect with sql authentication with the login "sc" and password "sc". I can also connect over tcp/ip using the prefix "tcp:" on the server name. But schemacrawler continues to rise an exception, that the connection failed. As host I have tried also to use "localhost" and the computer name, but nothing, the result is always the same.

```
Re-run SchemaCrawler with just the
-?
option for help

Or, re-run SchemaCrawler with an additional
-loglevel=CONFIG
option for details on the error
Aug 24, 2016 9:25:25 AM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: SchemaCrawler, v14.09.03
Aug 24, 2016 9:25:25 AM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: Command line:
-c=graph
-server=sqlserver
-host=127.0.0.1
-port=1433
-user=sc
-password=*****
-database=MasterData
-schema=MasterData.dbo
-infolevel=detailed
-loglevel=config
Aug 24, 2016 9:25:25 AM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Could not connect to jdbc:jtds:sqlserver://127.0.0.1:1433/MasterData;appName=SchemaCrawler;useCursors=true, for user 'sc', with properties {}
schemacrawler.schemacrawler.SchemaCrawlerSQLException: Could not connect to jdbc:jtds:sqlserver://127.0.0.1:1433/MasterData;appName=SchemaCrawler;useCursors=true, for user 'sc', with properties {}
        at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getConnection(BaseDatabaseConnectionOptions.java:157)
        at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getConnection(BaseDatabaseConnectionOptions.java:102)
        at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:131)
        at schemacrawler.Main.main(Main.java:91)
Caused by: java.sql.SQLException: Network error IOException: Connection refused: connect
        at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:436)
        at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:184)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getConnection(BaseDatabaseConnectionOptions.java:145)
        ... 3 more
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at net.sourceforge.jtds.jdbc.SharedSocket.createSocketForJDBC3(SharedSocket.java:288)
        at net.sourceforge.jtds.jdbc.SharedSocket.<init>(SharedSocket.java:251)
        at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:331)
        ... 7 more
```

**Comment by sualeh** [comment]
Please use the URL version of SchemaCrawler command-line, and follow the instructions to construct a URL in [jTDS FAQs](http://jtds.sourceforge.net/faq.html)
